name: ci

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24.1.0
          cache: pnpm
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - run: pnpm run test
      - name: Compile sass
        run: pnpm run sass-prod
      - name: Test rollup build
        run: pnpm run prod
